Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false